### ISSUE TITLE
One-year old quote each day

### ISSUE THREAD

**Issue by jsilvestre** [vaz-ar/goxxx#20]
It would be marvelous, fantastic, awesome, that each day we can have a quote from the same day, one year ago.

I don't do Go, but I have full trust in the great maintainers of Goxxx to perform a QUICK piece of code for this feature! <3

**Comment by vaz-ar** [comment]
done 0fcbb02edb22812c7d7a143909be9731777bc84a

**Comment by jsilvestre** [comment]
THANK YOU SIR.
